apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-agent-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentinel-agent-role
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentinel-agent-binding
subjects:
- kind: ServiceAccount
  name: sentinel-agent-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: sentinel-agent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-agent
  template:
    metadata:
      labels:
        app: sentinel-agent
    spec:
      serviceAccountName: sentinel-agent-sa
      containers:
      - name: agent
        image: sentinel-agent:v1
        imagePullPolicy: Never
        env:
        - name: BRAIN_URL
          value: "http://sentinel-brain:80/predict"